import Head from 'next/head'
import { useRouter } from 'next/router';
import { useContext } from 'react';
import { useQuery } from 'urql';
import { AuthContext } from './auth/context/AuthContext';
import { GET_ALL_EPROCESS } from 'graphql/queries';
import { Card } from 'primereact/card';
import { EProcessCard } from 'components/eprocess/components/EProcessCard';


export default function Home() {

  const router = useRouter();

  const [{ fetching, data }] = useQuery({ query: GET_ALL_EPROCESS });

  console.log(data?.getAllElectoralProcess);

  const { logout, user } = useContext(AuthContext);

  // const closeSession = () => {
  //   logout();
  //   router.replace('/auth/login');
  // }

  return (
    <>
      <Head>
        <title>Inicio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className="bg-white border-gray-200 dark:bg-gray-900">
        <div className="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-3">
          <a href="" className="flex items-center">
            {/* <img src="https://flowbite.com/docs/images/logo.svg" className="h-8 mr-3" alt="Flowbite Logo" /> */}
            <span className="self-center text-xl font-semibold whitespace-nowrap dark:text-white">Inicio</span>
          </a>
        </div>
      </nav>
      <main className="p-4">
        <h1 className="text-lg font-semibold">Procesos electorales activos</h1>
        {fetching && <h3>Loading...</h3>}
        {
          data && (
            <div className="flex flex-row gap-4 mt-4">
              {
                data.getAllElectoralProcess.map((e: any) => (
                  <EProcessCard
                    key={e.id}
                    id={e.id}
                    name={e.name}
                    processDate={e.processDate}
                    initialHour={e.initialHour}
                    finalHour={e.finalHour}
                  />
                ))
              }
            </div>
          )
        }
      </main>
    </>
  )
}
